// This file is generated by tauri-command-sdk-generator.
// Do not edit by hand.

import { invoke } from '@tauri-apps/api/core'
import type { BackgroundSettings } from './types'

export type AppSettingsGetBackgroundRequest = undefined
export type AppSettingsGetBackgroundResponse = BackgroundSettings

export type AppSettingsSetBackgroundRequest = {
  enabled: boolean
}
export type AppSettingsSetBackgroundResponse = BackgroundSettings

export type AppCommandSpec = {
  'app_settings_get_background': {
    request: AppSettingsGetBackgroundRequest
    response: AppSettingsGetBackgroundResponse
  }
  'app:settings_get_background': {
    request: AppSettingsGetBackgroundRequest
    response: AppSettingsGetBackgroundResponse
  }
  'app_settings_set_background': {
    request: AppSettingsSetBackgroundRequest
    response: AppSettingsSetBackgroundResponse
  }
  'app:settings_set_background': {
    request: AppSettingsSetBackgroundRequest
    response: AppSettingsSetBackgroundResponse
  }
}

/**
 * 获取后台运行设置。
 *
 * 参数约束：设置由后端从应用数据目录读取，不接收前端路径。
 * 返回含义：返回关闭窗口时是否允许隐藏到托盘。
 *
 * @returns Promise<AppSettingsGetBackgroundResponse>
 */
export function appSettingsGetBackground(): Promise<AppSettingsGetBackgroundResponse> {
  return invoke<AppSettingsGetBackgroundResponse>('app_settings_get_background')
}

/**
 * 更新后台运行设置。
 *
 * 参数约束：`enabled` 表示关闭窗口时是否允许隐藏到托盘。
 * 返回含义：返回保存后的后台运行设置。
 *
 * @param args AppSettingsSetBackgroundRequest
 * @returns Promise<AppSettingsSetBackgroundResponse>
 */
export function appSettingsSetBackground(args: AppSettingsSetBackgroundRequest): Promise<AppSettingsSetBackgroundResponse> {
  return invoke<AppSettingsSetBackgroundResponse>('app_settings_set_background', args)
}

