// This file is generated by tauri-command-sdk-generator.
// Do not edit by hand.

import { invoke } from '@tauri-apps/api/core'
import type { JobSnapshot, RenameExecuteRequest, RenamePlan, RenamePreviewRequest } from './types'

export type BatchRenameExecuteRequest = {
  request: RenameExecuteRequest
}
export type BatchRenameExecuteResponse = JobSnapshot

export type BatchRenamePreviewRequest = {
  request: RenamePreviewRequest
}
export type BatchRenamePreviewResponse = RenamePlan

export type BatchCommandSpec = {
  'batch_rename_execute': {
    request: BatchRenameExecuteRequest
    response: BatchRenameExecuteResponse
  }
  'batch:rename_execute': {
    request: BatchRenameExecuteRequest
    response: BatchRenameExecuteResponse
  }
  'batch_rename_preview': {
    request: BatchRenamePreviewRequest
    response: BatchRenamePreviewResponse
  }
  'batch:rename_preview': {
    request: BatchRenamePreviewRequest
    response: BatchRenamePreviewResponse
  }
}

/**
 * 执行批量重命名。
 *
 * 参数约束：`request` 必须引用有效预览计划，可携带用户勾选的原始路径。
 * 返回含义：返回代表本次执行结果的任务快照。
 *
 * @param args BatchRenameExecuteRequest
 * @returns Promise<BatchRenameExecuteResponse>
 */
export function batchRenameExecute(args: BatchRenameExecuteRequest): Promise<BatchRenameExecuteResponse> {
  return invoke<BatchRenameExecuteResponse>('batch_rename_execute', args)
}

/**
 * 预览批量重命名。
 *
 * 参数约束：`request.root` 必须位于已授权文件根下，规则由后端解析。
 * 返回含义：返回批量重命名计划、条目预览和确认 token。
 *
 * @param args BatchRenamePreviewRequest
 * @returns Promise<BatchRenamePreviewResponse>
 */
export function batchRenamePreview(args: BatchRenamePreviewRequest): Promise<BatchRenamePreviewResponse> {
  return invoke<BatchRenamePreviewResponse>('batch_rename_preview', args)
}

