// This file is generated by tauri-command-sdk-generator.
// Do not edit by hand.

import { invoke } from '@tauri-apps/api/core'
import type { AuthorizedRoot, FileEntry, FileLocations, FileOperationPlan, FileOperationRequest, FileRecursiveListRequest } from './types'

export type FileAuthorizePathRequest = {
  path: string
  label?: string | undefined
}
export type FileAuthorizePathResponse = AuthorizedRoot

export type FileExecuteOperationRequest = {
  planId: string
  confirmationToken: string
}
export type FileExecuteOperationResponse = FileEntry | undefined

export type FileGetLocationsRequest = undefined
export type FileGetLocationsResponse = FileLocations

export type FileListDirRequest = {
  path: string
}
export type FileListDirResponse = FileEntry[]

export type FileListDirRecursiveRequest = {
  request: FileRecursiveListRequest
}
export type FileListDirRecursiveResponse = FileEntry[]

export type FileListRootsRequest = undefined
export type FileListRootsResponse = AuthorizedRoot[]

export type FilePreviewOperationRequest = {
  request: FileOperationRequest
}
export type FilePreviewOperationResponse = FileOperationPlan

export type FileReadTextRequest = {
  path: string
}
export type FileReadTextResponse = string

export type FileCommandSpec = {
  'file_authorize_path': {
    request: FileAuthorizePathRequest
    response: FileAuthorizePathResponse
  }
  'file:authorize_path': {
    request: FileAuthorizePathRequest
    response: FileAuthorizePathResponse
  }
  'file_execute_operation': {
    request: FileExecuteOperationRequest
    response: FileExecuteOperationResponse
  }
  'file:execute_operation': {
    request: FileExecuteOperationRequest
    response: FileExecuteOperationResponse
  }
  'file_get_locations': {
    request: FileGetLocationsRequest
    response: FileGetLocationsResponse
  }
  'file:get_locations': {
    request: FileGetLocationsRequest
    response: FileGetLocationsResponse
  }
  'file_list_dir': {
    request: FileListDirRequest
    response: FileListDirResponse
  }
  'file:list_dir': {
    request: FileListDirRequest
    response: FileListDirResponse
  }
  'file_list_dir_recursive': {
    request: FileListDirRecursiveRequest
    response: FileListDirRecursiveResponse
  }
  'file:list_dir_recursive': {
    request: FileListDirRecursiveRequest
    response: FileListDirRecursiveResponse
  }
  'file_list_roots': {
    request: FileListRootsRequest
    response: FileListRootsResponse
  }
  'file:list_roots': {
    request: FileListRootsRequest
    response: FileListRootsResponse
  }
  'file_preview_operation': {
    request: FilePreviewOperationRequest
    response: FilePreviewOperationResponse
  }
  'file:preview_operation': {
    request: FilePreviewOperationRequest
    response: FilePreviewOperationResponse
  }
  'file_read_text': {
    request: FileReadTextRequest
    response: FileReadTextResponse
  }
  'file:read_text': {
    request: FileReadTextRequest
    response: FileReadTextResponse
  }
}

/**
 * 授权一个文件系统路径。
 *
 * 参数约束：`path` 来自系统选择器；文件路径会授权其父目录。
 * 返回含义：返回新增或更新后的授权根。
 *
 * @param args FileAuthorizePathRequest
 * @returns Promise<FileAuthorizePathResponse>
 */
export function fileAuthorizePath(args: FileAuthorizePathRequest): Promise<FileAuthorizePathResponse> {
  return invoke<FileAuthorizePathResponse>('file_authorize_path', args)
}

/**
 * 执行文件操作。
 *
 * 参数约束：`planId` 和 `confirmationToken` 必须来自有效的预览计划。
 * 返回含义：返回执行后相关文件条目；无相关条目时返回空值。
 *
 * @param args FileExecuteOperationRequest
 * @returns Promise<FileExecuteOperationResponse>
 */
export function fileExecuteOperation(args: FileExecuteOperationRequest): Promise<FileExecuteOperationResponse> {
  return invoke<FileExecuteOperationResponse>('file_execute_operation', args)
}

/**
 * 获取常用文件位置。
 *
 * 参数约束：由后端读取当前目录和可执行文件目录，不接收前端路径。
 * 返回含义：返回当前工作目录和程序目录。
 *
 * @returns Promise<FileGetLocationsResponse>
 */
export function fileGetLocations(): Promise<FileGetLocationsResponse> {
  return invoke<FileGetLocationsResponse>('file_get_locations')
}

/**
 * 列出目录内容。
 *
 * 参数约束：`path` 必须位于已授权文件根下。
 * 返回含义：返回该目录下的文件和子目录条目。
 *
 * @param args FileListDirRequest
 * @returns Promise<FileListDirResponse>
 */
export function fileListDir(args: FileListDirRequest): Promise<FileListDirResponse> {
  return invoke<FileListDirResponse>('file_list_dir', args)
}

/**
 * 递归列出目录内容。
 *
 * 参数约束：`request.path` 必须位于已授权文件根下，递归深度由 `maxDepth` 限制。
 * 返回含义：返回符合扩展名和文件类型条件的条目列表。
 *
 * @param args FileListDirRecursiveRequest
 * @returns Promise<FileListDirRecursiveResponse>
 */
export function fileListDirRecursive(args: FileListDirRecursiveRequest): Promise<FileListDirRecursiveResponse> {
  return invoke<FileListDirRecursiveResponse>('file_list_dir_recursive', args)
}

/**
 * 列出已授权文件根。
 *
 * 参数约束：包含静态安全根和用户通过选择器授权的动态根。
 * 返回含义：返回当前可访问的根目录列表。
 *
 * @returns Promise<FileListRootsResponse>
 */
export function fileListRoots(): Promise<FileListRootsResponse> {
  return invoke<FileListRootsResponse>('file_list_roots')
}

/**
 * 预览文件操作。
 *
 * 参数约束：`request` 描述写入、删除、重命名或创建操作，目标路径必须已授权。
 * 返回含义：返回需要确认的文件操作计划和确认 token。
 *
 * @param args FilePreviewOperationRequest
 * @returns Promise<FilePreviewOperationResponse>
 */
export function filePreviewOperation(args: FilePreviewOperationRequest): Promise<FilePreviewOperationResponse> {
  return invoke<FilePreviewOperationResponse>('file_preview_operation', args)
}

/**
 * 读取文本文件。
 *
 * 参数约束：`path` 必须位于已授权文件根下，且文件大小受后端限制。
 * 返回含义：返回文本文件内容。
 *
 * @param args FileReadTextRequest
 * @returns Promise<FileReadTextResponse>
 */
export function fileReadText(args: FileReadTextRequest): Promise<FileReadTextResponse> {
  return invoke<FileReadTextResponse>('file_read_text', args)
}

