// This file is generated by tauri-command-sdk-generator.
// Do not edit by hand.

import { invoke } from '@tauri-apps/api/core'
import type { HostEntry, HostsChangePlan, HostsChangeRequest, HostsHelperStatus } from './types'

export type HostsExecuteChangeRequest = {
  planId: string
  confirmationToken: string
}
export type HostsExecuteChangeResponse = HostEntry[]

export type HostsGetPathRequest = undefined
export type HostsGetPathResponse = string

export type HostsGetStatusRequest = undefined
export type HostsGetStatusResponse = HostsHelperStatus

export type HostsInstallHelperRequest = undefined
export type HostsInstallHelperResponse = HostsHelperStatus

export type HostsPreviewChangeRequest = {
  request: HostsChangeRequest
}
export type HostsPreviewChangeResponse = HostsChangePlan

export type HostsReadRequest = undefined
export type HostsReadResponse = HostEntry[]

export type HostsRepairHelperRequest = undefined
export type HostsRepairHelperResponse = HostsHelperStatus

export type HostsUninstallHelperRequest = undefined
export type HostsUninstallHelperResponse = HostsHelperStatus

export type HostsCommandSpec = {
  'hosts_execute_change': {
    request: HostsExecuteChangeRequest
    response: HostsExecuteChangeResponse
  }
  'hosts:execute_change': {
    request: HostsExecuteChangeRequest
    response: HostsExecuteChangeResponse
  }
  'hosts_get_path': {
    request: HostsGetPathRequest
    response: HostsGetPathResponse
  }
  'hosts:get_path': {
    request: HostsGetPathRequest
    response: HostsGetPathResponse
  }
  'hosts_get_status': {
    request: HostsGetStatusRequest
    response: HostsGetStatusResponse
  }
  'hosts:get_status': {
    request: HostsGetStatusRequest
    response: HostsGetStatusResponse
  }
  'hosts_install_helper': {
    request: HostsInstallHelperRequest
    response: HostsInstallHelperResponse
  }
  'hosts:install_helper': {
    request: HostsInstallHelperRequest
    response: HostsInstallHelperResponse
  }
  'hosts_preview_change': {
    request: HostsPreviewChangeRequest
    response: HostsPreviewChangeResponse
  }
  'hosts:preview_change': {
    request: HostsPreviewChangeRequest
    response: HostsPreviewChangeResponse
  }
  'hosts_read': {
    request: HostsReadRequest
    response: HostsReadResponse
  }
  'hosts:read': {
    request: HostsReadRequest
    response: HostsReadResponse
  }
  'hosts_repair_helper': {
    request: HostsRepairHelperRequest
    response: HostsRepairHelperResponse
  }
  'hosts:repair_helper': {
    request: HostsRepairHelperRequest
    response: HostsRepairHelperResponse
  }
  'hosts_uninstall_helper': {
    request: HostsUninstallHelperRequest
    response: HostsUninstallHelperResponse
  }
  'hosts:uninstall_helper': {
    request: HostsUninstallHelperRequest
    response: HostsUninstallHelperResponse
  }
}

/**
 * 执行 hosts 变更。
 *
 * 参数约束：`planId` 和 `confirmationToken` 必须来自有效 hosts 变更计划。
 * 返回含义：返回写入后的 hosts 条目列表。
 *
 * @param args HostsExecuteChangeRequest
 * @returns Promise<HostsExecuteChangeResponse>
 */
export function hostsExecuteChange(args: HostsExecuteChangeRequest): Promise<HostsExecuteChangeResponse> {
  return invoke<HostsExecuteChangeResponse>('hosts_execute_change', args)
}

/**
 * 获取 hosts 文件路径。
 *
 * 参数约束：由后端按当前平台决定路径，不接收前端参数。
 * 返回含义：返回当前系统 hosts 文件路径。
 *
 * @returns Promise<HostsGetPathResponse>
 */
export function hostsGetPath(): Promise<HostsGetPathResponse> {
  return invoke<HostsGetPathResponse>('hosts_get_path')
}

/**
 * 获取 hosts 写入辅助状态。
 *
 * 参数约束：由后端按当前平台探测，不接收前端参数。
 * 返回含义：返回是否需要高权限辅助以及当前辅助状态。
 *
 * @returns Promise<HostsGetStatusResponse>
 */
export function hostsGetStatus(): Promise<HostsGetStatusResponse> {
  return invoke<HostsGetStatusResponse>('hosts_get_status')
}

/**
 * 安装 hosts helper。
 *
 * 参数约束：只安装当前平台受支持的受限 hosts helper；安装过程会触发一次系统授权。
 * 返回含义：返回安装后的 helper 状态。
 *
 * @returns Promise<HostsInstallHelperResponse>
 */
export function hostsInstallHelper(): Promise<HostsInstallHelperResponse> {
  return invoke<HostsInstallHelperResponse>('hosts_install_helper')
}

/**
 * 预览 hosts 变更。
 *
 * 参数约束：`request` 只允许 add、remove、toggle 三类 hosts 变更。
 * 返回含义：返回 hosts 变更计划和确认 token。
 *
 * @param args HostsPreviewChangeRequest
 * @returns Promise<HostsPreviewChangeResponse>
 */
export function hostsPreviewChange(args: HostsPreviewChangeRequest): Promise<HostsPreviewChangeResponse> {
  return invoke<HostsPreviewChangeResponse>('hosts_preview_change', args)
}

/**
 * 读取 hosts 记录。
 *
 * 参数约束：读取系统 hosts 文件，不接收前端路径。
 * 返回含义：返回解析后的 hosts 条目列表。
 *
 * @returns Promise<HostsReadResponse>
 */
export function hostsRead(): Promise<HostsReadResponse> {
  return invoke<HostsReadResponse>('hosts_read')
}

/**
 * 修复 hosts helper。
 *
 * 参数约束：只更新本应用注册的 hosts helper 路径与 token 配置；修复过程会触发一次系统授权。
 * 返回含义：返回修复后的 helper 状态。
 *
 * @returns Promise<HostsRepairHelperResponse>
 */
export function hostsRepairHelper(): Promise<HostsRepairHelperResponse> {
  return invoke<HostsRepairHelperResponse>('hosts_repair_helper')
}

/**
 * 卸载 hosts helper。
 *
 * 参数约束：只卸载本应用注册的 hosts helper；卸载过程会触发一次系统授权。
 * 返回含义：返回卸载后的 helper 状态。
 *
 * @returns Promise<HostsUninstallHelperResponse>
 */
export function hostsUninstallHelper(): Promise<HostsUninstallHelperResponse> {
  return invoke<HostsUninstallHelperResponse>('hosts_uninstall_helper')
}

