// This file is generated by tauri-command-sdk-generator.
// Do not edit by hand.

export * from './types'
export * from './app'
export * from './batch'
export * from './file'
export * from './hosts'
export * from './jobs'
export * from './media'
export * from './mounts'
export * from './system'

import type { AppCommandSpec } from './app'
import type { BatchCommandSpec } from './batch'
import type { FileCommandSpec } from './file'
import type { HostsCommandSpec } from './hosts'
import type { JobsCommandSpec } from './jobs'
import type { MediaCommandSpec } from './media'
import type { MountsCommandSpec } from './mounts'
import type { SystemCommandSpec } from './system'

export type TauriCommandSpec =
  & AppCommandSpec
  & BatchCommandSpec
  & FileCommandSpec
  & HostsCommandSpec
  & JobsCommandSpec
  & MediaCommandSpec
  & MountsCommandSpec
  & SystemCommandSpec

export type TauriCommandName = keyof TauriCommandSpec

export type TauriCommandArgs = {
  [K in TauriCommandName]: TauriCommandSpec[K]['request']
}

export type TauriCommandResult = {
  [K in TauriCommandName]: TauriCommandSpec[K]['response']
}
