// This file is generated by tauri-command-sdk-generator.
// Do not edit by hand.

import { invoke } from '@tauri-apps/api/core'
import type { JobSnapshot } from './types'

export type JobsCancelRequest = {
  jobId: string
}
export type JobsCancelResponse = JobSnapshot

export type JobsGetRequest = {
  jobId: string
}
export type JobsGetResponse = JobSnapshot | undefined

export type JobsListRequest = undefined
export type JobsListResponse = JobSnapshot[]

export type JobsCommandSpec = {
  'jobs_cancel': {
    request: JobsCancelRequest
    response: JobsCancelResponse
  }
  'jobs:cancel': {
    request: JobsCancelRequest
    response: JobsCancelResponse
  }
  'jobs_get': {
    request: JobsGetRequest
    response: JobsGetResponse
  }
  'jobs:get': {
    request: JobsGetRequest
    response: JobsGetResponse
  }
  'jobs_list': {
    request: JobsListRequest
    response: JobsListResponse
  }
  'jobs:list': {
    request: JobsListRequest
    response: JobsListResponse
  }
}

/**
 * 取消指定任务。
 *
 * 参数约束：`jobId` 必须是后端任务 ID，已完成任务不会重新执行。
 * 返回含义：返回取消后的任务快照。
 *
 * @param args JobsCancelRequest
 * @returns Promise<JobsCancelResponse>
 */
export function jobsCancel(args: JobsCancelRequest): Promise<JobsCancelResponse> {
  return invoke<JobsCancelResponse>('jobs_cancel', args)
}

/**
 * 获取指定任务快照。
 *
 * 参数约束：`jobId` 必须是后端任务 ID。
 * 返回含义：返回任务快照；不存在时返回空值。
 *
 * @param args JobsGetRequest
 * @returns Promise<JobsGetResponse>
 */
export function jobsGet(args: JobsGetRequest): Promise<JobsGetResponse> {
  return invoke<JobsGetResponse>('jobs_get', args)
}

/**
 * 列出后台任务快照。
 *
 * 参数约束：只读取后端内存中的任务状态，不触发任务执行。
 * 返回含义：返回所有任务的当前快照列表。
 *
 * @returns Promise<JobsListResponse>
 */
export function jobsList(): Promise<JobsListResponse> {
  return invoke<JobsListResponse>('jobs_list')
}

