// This file is generated by tauri-command-sdk-generator.
// Do not edit by hand.

import { invoke } from '@tauri-apps/api/core'
import type { JobSnapshot, MediaPerformanceProfile, MediaPlan, MediaPlanRequest, MediaPreviewRequest, MediaProbeInfo, MediaRuntimeStatus } from './types'

export type MediaCreatePlanRequest = {
  request: MediaPlanRequest
}
export type MediaCreatePlanResponse = MediaPlan

export type MediaDownloadRuntimeRequest = undefined
export type MediaDownloadRuntimeResponse = MediaRuntimeStatus

export type MediaPerformanceProfileRequest = undefined
export type MediaPerformanceProfileResponse = MediaPerformanceProfile

export type MediaPreviewInputsRequest = {
  request: MediaPreviewRequest
}
export type MediaPreviewInputsResponse = string[]

export type MediaProbeVideoRequest = {
  path: string
}
export type MediaProbeVideoResponse = MediaProbeInfo

export type MediaRuntimeStatusRequest = undefined
export type MediaRuntimeStatusResponse = MediaRuntimeStatus

export type MediaStartJobRequest = {
  planId: string
  confirmationToken: string
}
export type MediaStartJobResponse = JobSnapshot

export type MediaCommandSpec = {
  'media_create_plan': {
    request: MediaCreatePlanRequest
    response: MediaCreatePlanResponse
  }
  'media:create_plan': {
    request: MediaCreatePlanRequest
    response: MediaCreatePlanResponse
  }
  'media_download_runtime': {
    request: MediaDownloadRuntimeRequest
    response: MediaDownloadRuntimeResponse
  }
  'media:download_runtime': {
    request: MediaDownloadRuntimeRequest
    response: MediaDownloadRuntimeResponse
  }
  'media_performance_profile': {
    request: MediaPerformanceProfileRequest
    response: MediaPerformanceProfileResponse
  }
  'media:performance_profile': {
    request: MediaPerformanceProfileRequest
    response: MediaPerformanceProfileResponse
  }
  'media_preview_inputs': {
    request: MediaPreviewInputsRequest
    response: MediaPreviewInputsResponse
  }
  'media:preview_inputs': {
    request: MediaPreviewInputsRequest
    response: MediaPreviewInputsResponse
  }
  'media_probe_video': {
    request: MediaProbeVideoRequest
    response: MediaProbeVideoResponse
  }
  'media:probe_video': {
    request: MediaProbeVideoRequest
    response: MediaProbeVideoResponse
  }
  'media_runtime_status': {
    request: MediaRuntimeStatusRequest
    response: MediaRuntimeStatusResponse
  }
  'media:runtime_status': {
    request: MediaRuntimeStatusRequest
    response: MediaRuntimeStatusResponse
  }
  'media_start_job': {
    request: MediaStartJobRequest
    response: MediaStartJobResponse
  }
  'media:start_job': {
    request: MediaStartJobRequest
    response: MediaStartJobResponse
  }
}

/**
 * 创建媒体处理计划。
 *
 * 参数约束：`request.inputs` 必须来自用户选择或授权目录预览。
 * 返回含义：返回媒体处理计划和确认 token。
 *
 * @param args MediaCreatePlanRequest
 * @returns Promise<MediaCreatePlanResponse>
 */
export function mediaCreatePlan(args: MediaCreatePlanRequest): Promise<MediaCreatePlanResponse> {
  return invoke<MediaCreatePlanResponse>('media_create_plan', args)
}

/**
 * 手动下载 FFmpeg 运行时。
 *
 * 参数约束：下载源由后端按当前平台固定选择，不接收前端 URL。
 * 返回含义：下载、校验并安装后返回新的 FFmpeg 运行时状态。
 *
 * @returns Promise<MediaDownloadRuntimeResponse>
 */
export function mediaDownloadRuntime(): Promise<MediaDownloadRuntimeResponse> {
  return invoke<MediaDownloadRuntimeResponse>('media_download_runtime')
}

/**
 * 获取媒体处理性能建议。
 *
 * 参数约束：由后端读取本机硬件和 FFmpeg 编码器能力，不接收前端参数。
 * 返回含义：返回设备摘要、可用编码器和推荐的 FFmpeg 参数。
 *
 * @returns Promise<MediaPerformanceProfileResponse>
 */
export function mediaPerformanceProfile(): Promise<MediaPerformanceProfileResponse> {
  return invoke<MediaPerformanceProfileResponse>('media_performance_profile')
}

/**
 * 预览媒体输入。
 *
 * 参数约束：`request.root` 必须位于已授权文件根下，按媒体类型和深度筛选。
 * 返回含义：返回符合条件的媒体文件路径列表。
 *
 * @param args MediaPreviewInputsRequest
 * @returns Promise<MediaPreviewInputsResponse>
 */
export function mediaPreviewInputs(args: MediaPreviewInputsRequest): Promise<MediaPreviewInputsResponse> {
  return invoke<MediaPreviewInputsResponse>('media_preview_inputs', args)
}

/**
 * 探测视频详情。
 *
 * 参数约束：`path` 必须位于已授权文件根下，且必须是文件。
 * 返回含义：返回 ffprobe 解析出的容器、时长、码率和流信息。
 *
 * @param args MediaProbeVideoRequest
 * @returns Promise<MediaProbeVideoResponse>
 */
export function mediaProbeVideo(args: MediaProbeVideoRequest): Promise<MediaProbeVideoResponse> {
  return invoke<MediaProbeVideoResponse>('media_probe_video', args)
}

/**
 * 获取媒体运行时状态。
 *
 * 参数约束：由后端探测 FFmpeg 状态，不接收前端参数。
 * 返回含义：返回 FFmpeg 是否可用以及版本或错误信息。
 *
 * @returns Promise<MediaRuntimeStatusResponse>
 */
export function mediaRuntimeStatus(): Promise<MediaRuntimeStatusResponse> {
  return invoke<MediaRuntimeStatusResponse>('media_runtime_status')
}

/**
 * 启动媒体任务。
 *
 * 参数约束：`planId` 和 `confirmationToken` 必须来自有效媒体计划。
 * 返回含义：返回启动后的任务快照。
 *
 * @param args MediaStartJobRequest
 * @returns Promise<MediaStartJobResponse>
 */
export function mediaStartJob(args: MediaStartJobRequest): Promise<MediaStartJobResponse> {
  return invoke<MediaStartJobResponse>('media_start_job', args)
}

