// This file is generated by tauri-command-sdk-generator.
// Do not edit by hand.

import { invoke } from '@tauri-apps/api/core'
import type { ConnectionProbeResult, MountDependencyStatus, MountRuntimeStatus, MountUiContext, MountWorkspace, MountWorkspaceInput, RemoteConnection, RemoteConnectionInput } from './types'

export type MountsCheckDependenciesRequest = undefined
export type MountsCheckDependenciesResponse = MountDependencyStatus

export type MountsCreateWorkspaceRequest = {
  input: MountWorkspaceInput
}
export type MountsCreateWorkspaceResponse = MountWorkspace

export type MountsDeleteConnectionRequest = {
  id: string
}
export type MountsDeleteConnectionResponse = void

export type MountsDeleteWorkspaceRequest = {
  id: string
}
export type MountsDeleteWorkspaceResponse = void

export type MountsDownloadRuntimeRequest = undefined
export type MountsDownloadRuntimeResponse = MountRuntimeStatus

export type MountsGetRuntimeStatusRequest = undefined
export type MountsGetRuntimeStatusResponse = MountRuntimeStatus

export type MountsGetUiContextRequest = undefined
export type MountsGetUiContextResponse = MountUiContext

export type MountsListConnectionsRequest = undefined
export type MountsListConnectionsResponse = RemoteConnection[]

export type MountsListWorkspacesRequest = undefined
export type MountsListWorkspacesResponse = MountWorkspace[]

export type MountsProbeConnectionRequest = {
  connectionId: string
}
export type MountsProbeConnectionResponse = ConnectionProbeResult

export type MountsRefreshWorkspaceRequest = {
  id: string
  path?: string | undefined
}
export type MountsRefreshWorkspaceResponse = MountWorkspace

export type MountsRepairWorkspaceRequest = {
  id: string
}
export type MountsRepairWorkspaceResponse = MountWorkspace

export type MountsSaveConnectionRequest = {
  input: RemoteConnectionInput
}
export type MountsSaveConnectionResponse = RemoteConnection

export type MountsSetWorkspaceEnabledRequest = {
  id: string
  enabled: boolean
}
export type MountsSetWorkspaceEnabledResponse = MountWorkspace

export type MountsUnmountAllRequest = undefined
export type MountsUnmountAllResponse = void

export type MountsCommandSpec = {
  'mounts_check_dependencies': {
    request: MountsCheckDependenciesRequest
    response: MountsCheckDependenciesResponse
  }
  'mounts:check_dependencies': {
    request: MountsCheckDependenciesRequest
    response: MountsCheckDependenciesResponse
  }
  'mounts_create_workspace': {
    request: MountsCreateWorkspaceRequest
    response: MountsCreateWorkspaceResponse
  }
  'mounts:create_workspace': {
    request: MountsCreateWorkspaceRequest
    response: MountsCreateWorkspaceResponse
  }
  'mounts_delete_connection': {
    request: MountsDeleteConnectionRequest
    response: MountsDeleteConnectionResponse
  }
  'mounts:delete_connection': {
    request: MountsDeleteConnectionRequest
    response: MountsDeleteConnectionResponse
  }
  'mounts_delete_workspace': {
    request: MountsDeleteWorkspaceRequest
    response: MountsDeleteWorkspaceResponse
  }
  'mounts:delete_workspace': {
    request: MountsDeleteWorkspaceRequest
    response: MountsDeleteWorkspaceResponse
  }
  'mounts_download_runtime': {
    request: MountsDownloadRuntimeRequest
    response: MountsDownloadRuntimeResponse
  }
  'mounts:download_runtime': {
    request: MountsDownloadRuntimeRequest
    response: MountsDownloadRuntimeResponse
  }
  'mounts_get_runtime_status': {
    request: MountsGetRuntimeStatusRequest
    response: MountsGetRuntimeStatusResponse
  }
  'mounts:get_runtime_status': {
    request: MountsGetRuntimeStatusRequest
    response: MountsGetRuntimeStatusResponse
  }
  'mounts_get_ui_context': {
    request: MountsGetUiContextRequest
    response: MountsGetUiContextResponse
  }
  'mounts:get_ui_context': {
    request: MountsGetUiContextRequest
    response: MountsGetUiContextResponse
  }
  'mounts_list_connections': {
    request: MountsListConnectionsRequest
    response: MountsListConnectionsResponse
  }
  'mounts:list_connections': {
    request: MountsListConnectionsRequest
    response: MountsListConnectionsResponse
  }
  'mounts_list_workspaces': {
    request: MountsListWorkspacesRequest
    response: MountsListWorkspacesResponse
  }
  'mounts:list_workspaces': {
    request: MountsListWorkspacesRequest
    response: MountsListWorkspacesResponse
  }
  'mounts_probe_connection': {
    request: MountsProbeConnectionRequest
    response: MountsProbeConnectionResponse
  }
  'mounts:probe_connection': {
    request: MountsProbeConnectionRequest
    response: MountsProbeConnectionResponse
  }
  'mounts_refresh_workspace': {
    request: MountsRefreshWorkspaceRequest
    response: MountsRefreshWorkspaceResponse
  }
  'mounts:refresh_workspace': {
    request: MountsRefreshWorkspaceRequest
    response: MountsRefreshWorkspaceResponse
  }
  'mounts_repair_workspace': {
    request: MountsRepairWorkspaceRequest
    response: MountsRepairWorkspaceResponse
  }
  'mounts:repair_workspace': {
    request: MountsRepairWorkspaceRequest
    response: MountsRepairWorkspaceResponse
  }
  'mounts_save_connection': {
    request: MountsSaveConnectionRequest
    response: MountsSaveConnectionResponse
  }
  'mounts:save_connection': {
    request: MountsSaveConnectionRequest
    response: MountsSaveConnectionResponse
  }
  'mounts_set_workspace_enabled': {
    request: MountsSetWorkspaceEnabledRequest
    response: MountsSetWorkspaceEnabledResponse
  }
  'mounts:set_workspace_enabled': {
    request: MountsSetWorkspaceEnabledRequest
    response: MountsSetWorkspaceEnabledResponse
  }
  'mounts_unmount_all': {
    request: MountsUnmountAllRequest
    response: MountsUnmountAllResponse
  }
  'mounts:unmount_all': {
    request: MountsUnmountAllRequest
    response: MountsUnmountAllResponse
  }
}

export function mountsCheckDependencies(): Promise<MountsCheckDependenciesResponse> {
  return invoke<MountsCheckDependenciesResponse>('mounts_check_dependencies')
}

export function mountsCreateWorkspace(args: MountsCreateWorkspaceRequest): Promise<MountsCreateWorkspaceResponse> {
  return invoke<MountsCreateWorkspaceResponse>('mounts_create_workspace', args)
}

export function mountsDeleteConnection(args: MountsDeleteConnectionRequest): Promise<MountsDeleteConnectionResponse> {
  return invoke<MountsDeleteConnectionResponse>('mounts_delete_connection', args)
}

export function mountsDeleteWorkspace(args: MountsDeleteWorkspaceRequest): Promise<MountsDeleteWorkspaceResponse> {
  return invoke<MountsDeleteWorkspaceResponse>('mounts_delete_workspace', args)
}

export function mountsDownloadRuntime(): Promise<MountsDownloadRuntimeResponse> {
  return invoke<MountsDownloadRuntimeResponse>('mounts_download_runtime')
}

export function mountsGetRuntimeStatus(): Promise<MountsGetRuntimeStatusResponse> {
  return invoke<MountsGetRuntimeStatusResponse>('mounts_get_runtime_status')
}

export function mountsGetUiContext(): Promise<MountsGetUiContextResponse> {
  return invoke<MountsGetUiContextResponse>('mounts_get_ui_context')
}

export function mountsListConnections(): Promise<MountsListConnectionsResponse> {
  return invoke<MountsListConnectionsResponse>('mounts_list_connections')
}

export function mountsListWorkspaces(): Promise<MountsListWorkspacesResponse> {
  return invoke<MountsListWorkspacesResponse>('mounts_list_workspaces')
}

export function mountsProbeConnection(args: MountsProbeConnectionRequest): Promise<MountsProbeConnectionResponse> {
  return invoke<MountsProbeConnectionResponse>('mounts_probe_connection', args)
}

export function mountsRefreshWorkspace(args: MountsRefreshWorkspaceRequest): Promise<MountsRefreshWorkspaceResponse> {
  return invoke<MountsRefreshWorkspaceResponse>('mounts_refresh_workspace', args)
}

export function mountsRepairWorkspace(args: MountsRepairWorkspaceRequest): Promise<MountsRepairWorkspaceResponse> {
  return invoke<MountsRepairWorkspaceResponse>('mounts_repair_workspace', args)
}

export function mountsSaveConnection(args: MountsSaveConnectionRequest): Promise<MountsSaveConnectionResponse> {
  return invoke<MountsSaveConnectionResponse>('mounts_save_connection', args)
}

export function mountsSetWorkspaceEnabled(args: MountsSetWorkspaceEnabledRequest): Promise<MountsSetWorkspaceEnabledResponse> {
  return invoke<MountsSetWorkspaceEnabledResponse>('mounts_set_workspace_enabled', args)
}

export function mountsUnmountAll(): Promise<MountsUnmountAllResponse> {
  return invoke<MountsUnmountAllResponse>('mounts_unmount_all')
}

