// This file is generated by tauri-command-sdk-generator.
// Do not edit by hand.

import { invoke } from '@tauri-apps/api/core'
import type { HardwareInfo, SystemOverview } from './types'

export type SystemHardwareInfoRequest = undefined
export type SystemHardwareInfoResponse = HardwareInfo

export type SystemOverviewRequest = undefined
export type SystemOverviewResponse = SystemOverview

export type SystemCommandSpec = {
  'system_hardware_info': {
    request: SystemHardwareInfoRequest
    response: SystemHardwareInfoResponse
  }
  'system:hardware_info': {
    request: SystemHardwareInfoRequest
    response: SystemHardwareInfoResponse
  }
  'system_overview': {
    request: SystemOverviewRequest
    response: SystemOverviewResponse
  }
  'system:overview': {
    request: SystemOverviewRequest
    response: SystemOverviewResponse
  }
}

/**
 * 获取硬件信息。
 *
 * 参数约束：由后端读取当前设备硬件信息，不接收前端参数。
 * 返回含义：返回操作系统、CPU、内存、主板和显卡摘要。
 *
 * @returns Promise<SystemHardwareInfoResponse>
 */
export function systemHardwareInfo(): Promise<SystemHardwareInfoResponse> {
  return invoke<SystemHardwareInfoResponse>('system_hardware_info')
}

/**
 * 获取系统运行概览。
 *
 * 参数约束：由后端读取应用目录、当前目录和平台信息，不接收前端参数。
 * 返回含义：返回应用数据目录、当前目录、平台和运行时策略。
 *
 * @returns Promise<SystemOverviewResponse>
 */
export function systemOverview(): Promise<SystemOverviewResponse> {
  return invoke<SystemOverviewResponse>('system_overview')
}

