// This file is generated by tauri-command-sdk-generator.
// Do not edit by hand.

export type AppError = {
  code: string
  message: string
  detail?: string | undefined
  recoverable: boolean
}

export type AuthorizedRoot = {
  id: string
  label: string
  path: string
}

export type BackgroundSettings = {
  enabled: boolean
}

export type ConnectionProbeResult = {
  connectionId: string
  smb: TransportProbeResult
  ftp: TransportProbeResult
  recommendedTransport?: EffectiveTransport | undefined
  fallbackReason?: string | undefined
  probedAt: number
}

export type EffectiveTransport = 'nativeSmb' | 'ftpCombine'

export type FileEntry = {
  name: string
  path: string
  parent: string
  isDir: boolean
  size: number
  modifiedAt?: number | undefined
  readonly: boolean
}

export type FileLocations = {
  currentDir: string
  executableDir: string
}

export type FileOperationKind = 'writeText' | 'delete' | 'rename' | 'createFile' | 'createDir'

export type FileOperationPlan = {
  id: string
  kind: FileOperationKind
  targetPath: string
  summary: string
  risk: OperationRisk
  requiresConfirmation: boolean
  confirmationToken: string
  createdAt: number
}

export type FileOperationRequest = { kind: 'writeText'; path: string; content: string } | { kind: 'delete'; path: string; recursive?: boolean | undefined } | { kind: 'rename'; path: string; newName: string } | { kind: 'createFile'; path: string } | { kind: 'createDir'; path: string }

export type FileRecursiveListRequest = {
  path: string
  maxDepth: number
  extensions?: string[] | undefined
  filesOnly?: boolean | undefined
}

export type GpuInfo = {
  name: string
  vram: string
}

export type HardwareInfo = {
  osName: string
  osVersion: string
  hostname: string
  cpuName: string
  cpuCores: number
  motherboard: string
  ramTotal: number
  ramUsed: number
  swapTotal: number
  swapUsed: number
  gpuInfo: GpuInfo[]
}

export type HostEntry = {
  raw: string
  ip?: string | undefined
  hosts: string[]
  enabled: boolean
  isCommentOrBlank: boolean
}

export type HostsChangeAction = 'add' | 'remove' | 'toggle'

export type HostsChangePlan = {
  id: string
  summary: string
  lineCount: number
  confirmationToken: string
}

export type HostsChangeRequest = {
  action: HostsChangeAction
  ip?: string | undefined
  host: string
  enabled?: boolean | undefined
}

export type HostsHelperStatus = {
  required: boolean
  installed: boolean
  running: boolean
  tokenExists: boolean
  needsRepair: boolean
  serviceName?: string | undefined
  platform: string
  helperKind?: string | undefined
  installSupported: boolean
  message: string
}

export type ImageOutputFormat = 'webp' | 'avif'

export type JobProgressItem = {
  id: string
  inputPath: string
  label: string
  status: JobProgressItemStatus
  progress: number
  message: string
  currentTarget?: string | undefined
  frame?: number | undefined
  totalFrames?: number | undefined
  completedTargets: number
  totalTargets: number
  artifacts: string[]
  error?: string | undefined
}

export type JobProgressItemStatus = 'queued' | 'running' | 'succeeded' | 'failed' | 'cancelled'

export type JobResult = {
  executor: string
  completed: boolean
  artifacts: string[]
}

export type JobSnapshot = {
  id: string
  kind: string
  title: string
  status: JobStatus
  progress: number
  message: string
  createdAt: number
  updatedAt: number
  progressItems: JobProgressItem[]
  result?: JobResult | undefined
  error?: AppError | undefined
}

export type JobStatus = 'queued' | 'running' | 'succeeded' | 'failed' | 'cancelled'

export type MediaDeviceSummary = {
  cpuName: string
  cpuPhysicalCores: number
  cpuLogicalCores: number
  ramTotal: number
  ramAvailable: number
  gpus: MediaGpuSummary[]
}

export type MediaEncoderCapability = {
  encoder: VideoAv1Encoder
  ffmpegName: string
  available: boolean
  hardware: boolean
  description: string
}

export type MediaGpuSummary = {
  name: string
  vramBytes?: number | undefined
  driverVersion?: string | undefined
}

export type MediaJobKind = 'imageCompression' | 'videoTranscode'

export type MediaPerformanceProfile = {
  device: MediaDeviceSummary
  encoders: MediaEncoderCapability[]
  recommended: MediaRecommendedSettings
  message: string
}

export type MediaPlan = {
  id: string
  kind: MediaJobKind
  summary: string
  inputs: string[]
  outputDir?: string | undefined
  confirmationToken: string
}

export type MediaPlanRequest = {
  kind: MediaJobKind
  inputs: string[]
  outputDir?: string | undefined
  sourceRoot?: string | undefined
  imageFormat?: ImageOutputFormat | undefined
  quality?: number | undefined
  cornerRadius?: string | undefined
  maxDepth?: number | undefined
  videoTargets?: VideoTarget[] | undefined
  webpQuality?: number | undefined
  av1Encoder?: VideoAv1Encoder | undefined
  av1Speed?: number | undefined
  av1Crf?: number | undefined
  av1Threads?: number | undefined
  av1TileColumns?: number | undefined
  av1TileRows?: number | undefined
  videoConcurrency?: number | undefined
  hqdnLumaSpatial?: number | undefined
  hqdnChromaSpatial?: number | undefined
  hqdnLumaTemporal?: number | undefined
  hqdnChromaTemporal?: number | undefined
}

export type MediaPreviewRequest = {
  root: string
  kind: MediaJobKind
  maxDepth: number
}

export type MediaProbeInfo = {
  path: string
  name: string
  formatName?: string | undefined
  formatLongName?: string | undefined
  durationSeconds?: number | undefined
  sizeBytes?: number | undefined
  bitrateBps?: number | undefined
  streams: MediaProbeStream[]
  rawSummary: string
}

export type MediaProbeStream = {
  index: number
  codecType?: string | undefined
  codecName?: string | undefined
  codecLongName?: string | undefined
  profile?: string | undefined
  width?: number | undefined
  height?: number | undefined
  frameRate?: string | undefined
  pixelFormat?: string | undefined
  sampleRate?: number | undefined
  channels?: number | undefined
  channelLayout?: string | undefined
  durationSeconds?: number | undefined
  bitrateBps?: number | undefined
  language?: string | undefined
  title?: string | undefined
}

export type MediaRecommendedSettings = {
  av1Encoder: VideoAv1Encoder
  av1Speed: number
  av1Crf: number
  av1Threads: number
  av1TileColumns: number
  av1TileRows: number
  videoConcurrency: number
  summary: string
  ffmpegArgs: string[]
}

export type MediaRuntimeStatus = {
  ffmpegVersion?: string | undefined
  path?: string | undefined
  sourceName?: string | undefined
  sourceUrl?: string | undefined
  downloadSupported: boolean
  message: string
  ready: boolean
}

export type MountAdvancedOptions = {
  dirCacheTime: string
  vfsCacheMaxSize: string
  vfsCacheMaxAge: string
  vfsReadChunkSize: string
  bufferSize: string
  pollInterval: string
  links: boolean
  networkMode: boolean
  connectTimeout: string
  ioTimeout: string
  retries: number
  lowLevelRetries: number
  retriesSleep: string
}

export type MountDependencyStatus = {
  supported: boolean
  ready: boolean
  dependencyName: string
  installed: boolean
  installUrl?: string | undefined
  message: string
}

export type MountPlatform = 'windows' | 'macos' | 'linux' | 'unknown'

export type MountRuntimeStatus = {
  installed: boolean
  version?: string | undefined
  path: string
  expectedVersion: string
  downloadRequired: boolean
  sourceName?: string | undefined
  sourceUrl?: string | undefined
  downloadSupported: boolean
}

export type MountStatus = 'disabled' | 'stopped' | 'mounted'

export type MountUiContext = {
  platform: MountPlatform
  defaultMountRoot: string
  defaultMountExample: string
  defaultDriveLetter?: string | undefined
  defaultDriveLetters?: string[] | undefined
  configDir: string
  profileConfigPath: string
  rcloneConfigPath: string
  supportsDriveLetter: boolean
  message: string
}

export type MountWorkspace = {
  id: string
  connectionId: string
  name: string
  bindings: RemoteBinding[]
  driveLetter?: string | undefined
  mountPoint?: string | undefined
  advancedOptions: MountAdvancedOptions
  enabled: boolean
  createdAt: number
  updatedAt: number
  effectiveTransport?: EffectiveTransport | undefined
  mounted: boolean
  status: MountStatus
  error?: string | undefined
}

export type MountWorkspaceInput = {
  id?: string | undefined
  connectionId: string
  name: string
  bindings: RemoteBindingInput[]
  driveLetter?: string | undefined
  mountPoint?: string | undefined
  advancedOptions?: MountAdvancedOptions | undefined
  enabled?: boolean | undefined
  effectiveTransport?: EffectiveTransport | undefined
}

export type OperationRisk = 'low' | 'medium' | 'high'

export type ProbeShareEntry = {
  name: string
  path: string
  accessible: boolean
  error?: string | undefined
  suggestedDriveLetter?: string | undefined
  suggestedMountPoint?: string | undefined
}

export type RemoteBinding = {
  id: string
  name: string
  remotePath: string
  driveLetter?: string | undefined
  mountPoint?: string | undefined
  accessible: boolean
  error?: string | undefined
}

export type RemoteBindingInput = {
  name: string
  remotePath: string
  driveLetter?: string | undefined
  mountPoint?: string | undefined
}

export type RemoteConnection = {
  id: string
  name: string
  host: string
  username: string
  password?: string | undefined
  domain?: string | undefined
  ftpPort: number
  smbPort: number
  tlsMode?: string | undefined
  noCheckCertificate: boolean
  transportPreference: TransportPreference
  windowsAuthMode: WindowsSmbAuthMode
  createdAt: number
  updatedAt: number
}

export type RemoteConnectionInput = {
  id?: string | undefined
  name: string
  host: string
  username: string
  password?: string | undefined
  domain?: string | undefined
  ftpPort?: number | undefined
  smbPort?: number | undefined
  tlsMode?: string | undefined
  noCheckCertificate?: boolean | undefined
  transportPreference?: TransportPreference | undefined
  windowsAuthMode?: WindowsSmbAuthMode | undefined
}

export type RenameExecuteRequest = {
  planId: string
  confirmationToken: string
  selectedOriginalPaths?: string[] | undefined
}

export type RenamePlan = {
  id: string
  root: string
  items: RenamePreviewItem[]
  confirmationToken: string
}

export type RenamePreviewItem = {
  originalPath: string
  originalName: string
  newName: string
  selected: boolean
  collision: boolean
  autoResolved: boolean
}

export type RenamePreviewRequest = {
  root: string
  pattern: string
  replacement: string
  maxDepth: number
  preserveExtension: boolean
  useRegex?: boolean | undefined
  autoResolveCollision?: boolean | undefined
  collisionStartIndex?: number | undefined
}

export type SmbHostCleanupResult = {
  host: string
  removedCount: number
  disabledWorkspaceCount: number
  removedMappings: SmbMappingCleanupItem[]
}

export type SmbMappingCleanupItem = {
  localName?: string | undefined
  remoteName: string
}

export type SystemOverview = {
  appDataDir: string
  currentDir: string
  platform: string
  runtimePolicy: string
}

export type TransportPreference = 'auto' | 'smb' | 'ftp'

export type TransportProbeResult = {
  available: boolean
  authenticated: boolean
  message: string
  rawOutput: string
  entries: ProbeShareEntry[]
}

export type VideoAv1Encoder = 'auto' | 'av1Nvenc' | 'libSvtAv1' | 'libAomAv1'

export type VideoTarget = 'animatedWebp' | 'av1WithAudio' | 'av1VideoOnly' | 'audioMp3'

export type WindowsSmbAuthMode = 'auto' | 'plain' | 'domain'

